---

- name: ensure required directories are exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0644
  with_items:
    - "{{ curator.dirs.config }}"
    - "{{ curator.dirs.actions }}"
    - "{{ curator.config.logging.logfile | dirname }}"

- name: deliver curator configuration file
  copy:
    content: "{{ curator.config | to_nice_yaml }}"
    dest: "{{ curator.dirs.config }}/curator.yml"
    mode: 0644
    backup: true

- name: deliver curator action configs
  copy:
    content: "{{ item.value | to_nice_yaml }}"
    dest: "{{ curator.dirs.actions }}/{{ item.key }}.yml"
    mode: 0644
    backup: true
  with_dict: "{{ curator.action_configs }}"

- name: generate curator action configs
  template:
    src: project_index_rotation.yml.j2
    dest: "{{ curator.dirs.actions }}/project_index_rotation.yml"
    mode: 0644
    backup: true
  when: curator.project_index_rotation | length != 0

- name: configure cron jobs for curator
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
  with_items: "{{ curator.cron_jobs }}"
