---

- name: ensure dependencies are installed
  package:
    name:
      - python-apt
      - apt-transport-https

- name: ensure Elastic repository key is present
  apt_key:
    url: "http://packages.elastic.co/GPG-KEY-elasticsearch"

- name: ensure Curator repository is present
  apt_repository:
    repo: "deb http://packages.elastic.co/curator/5/debian9 stable main"
